namespace PoolScoreboard.Controller.Assets.Flags;

public enum FlagGroup
{
    State,
    Country
}

public record FlagIconEntry(string Label, FlagGroup Group, Uri PackUri);

/// <summary>
/// The bundled end-cap flag set: US states/territories and world countries, sourced from
/// github.com/nibsbin/us-state-flags-svg and github.com/lipis/flag-icons respectively (see
/// NOTES.md for licensing detail). Generated once from those repos' listings. File names are an
/// ASCII-only slug of each label (diacritics/punctuation stripped) — the display Label keeps the
/// original accented/punctuated name; only the on-disk file and pack URI are simplified, since
/// WPF's resource manifest encoding doesn't reliably round-trip commas/parentheses/diacritics
/// through Uri.EscapeDataString (confirmed via a runtime "Cannot locate resource" failure).
/// </summary>
public static class FlagCatalog
{
    private static Uri Pack(string folder, string fileName) =>
        new($"pack://application:,,,/Assets/Flags/{folder}/{Uri.EscapeDataString(fileName)}.svg", UriKind.Absolute);

    public static readonly IReadOnlyList<FlagIconEntry> States = new List<FlagIconEntry>
    {
        new("Alabama", FlagGroup.State, Pack("States", "Alabama")),
        new("Alaska", FlagGroup.State, Pack("States", "Alaska")),
        new("American Samoa", FlagGroup.State, Pack("States", "American Samoa")),
        new("Arizona", FlagGroup.State, Pack("States", "Arizona")),
        new("Arkansas", FlagGroup.State, Pack("States", "Arkansas")),
        new("California", FlagGroup.State, Pack("States", "California")),
        new("Colorado", FlagGroup.State, Pack("States", "Colorado")),
        new("Connecticut", FlagGroup.State, Pack("States", "Connecticut")),
        new("Delaware", FlagGroup.State, Pack("States", "Delaware")),
        new("District of Columbia", FlagGroup.State, Pack("States", "District of Columbia")),
        new("Florida", FlagGroup.State, Pack("States", "Florida")),
        new("Georgia", FlagGroup.State, Pack("States", "Georgia")),
        new("Guam", FlagGroup.State, Pack("States", "Guam")),
        new("Hawaii", FlagGroup.State, Pack("States", "Hawaii")),
        new("Idaho", FlagGroup.State, Pack("States", "Idaho")),
        new("Illinois", FlagGroup.State, Pack("States", "Illinois")),
        new("Indiana", FlagGroup.State, Pack("States", "Indiana")),
        new("Iowa", FlagGroup.State, Pack("States", "Iowa")),
        new("Kansas", FlagGroup.State, Pack("States", "Kansas")),
        new("Kentucky", FlagGroup.State, Pack("States", "Kentucky")),
        new("Louisiana", FlagGroup.State, Pack("States", "Louisiana")),
        new("Maine", FlagGroup.State, Pack("States", "Maine")),
        new("Maryland", FlagGroup.State, Pack("States", "Maryland")),
        new("Massachusetts", FlagGroup.State, Pack("States", "Massachusetts")),
        new("Michigan", FlagGroup.State, Pack("States", "Michigan")),
        new("Minnesota", FlagGroup.State, Pack("States", "Minnesota")),
        new("Mississippi", FlagGroup.State, Pack("States", "Mississippi")),
        new("Missouri", FlagGroup.State, Pack("States", "Missouri")),
        new("Montana", FlagGroup.State, Pack("States", "Montana")),
        new("Nebraska", FlagGroup.State, Pack("States", "Nebraska")),
        new("Nevada", FlagGroup.State, Pack("States", "Nevada")),
        new("New Hampshire", FlagGroup.State, Pack("States", "New Hampshire")),
        new("New Jersey", FlagGroup.State, Pack("States", "New Jersey")),
        new("New Mexico", FlagGroup.State, Pack("States", "New Mexico")),
        new("New York", FlagGroup.State, Pack("States", "New York")),
        new("North Carolina", FlagGroup.State, Pack("States", "North Carolina")),
        new("North Dakota", FlagGroup.State, Pack("States", "North Dakota")),
        new("Northern Mariana Islands", FlagGroup.State, Pack("States", "Northern Mariana Islands")),
        new("Ohio", FlagGroup.State, Pack("States", "Ohio")),
        new("Oklahoma", FlagGroup.State, Pack("States", "Oklahoma")),
        new("Oregon", FlagGroup.State, Pack("States", "Oregon")),
        new("Pennsylvania", FlagGroup.State, Pack("States", "Pennsylvania")),
        new("Puerto Rico", FlagGroup.State, Pack("States", "Puerto Rico")),
        new("Rhode Island", FlagGroup.State, Pack("States", "Rhode Island")),
        new("South Carolina", FlagGroup.State, Pack("States", "South Carolina")),
        new("South Dakota", FlagGroup.State, Pack("States", "South Dakota")),
        new("Tennessee", FlagGroup.State, Pack("States", "Tennessee")),
        new("Texas", FlagGroup.State, Pack("States", "Texas")),
        new("United States Virgin Islands", FlagGroup.State, Pack("States", "United States Virgin Islands")),
        new("Utah", FlagGroup.State, Pack("States", "Utah")),
        new("Vermont", FlagGroup.State, Pack("States", "Vermont")),
        new("Virginia", FlagGroup.State, Pack("States", "Virginia")),
        new("Washington", FlagGroup.State, Pack("States", "Washington")),
        new("West Virginia", FlagGroup.State, Pack("States", "West Virginia")),
        new("Wisconsin", FlagGroup.State, Pack("States", "Wisconsin")),
        new("Wyoming", FlagGroup.State, Pack("States", "Wyoming")),
    };

    public static readonly IReadOnlyList<FlagIconEntry> Countries = new List<FlagIconEntry>
    {
        new("Afghanistan", FlagGroup.Country, Pack("Countries", "Afghanistan")),
        new("Aland Islands", FlagGroup.Country, Pack("Countries", "Aland Islands")),
        new("Albania", FlagGroup.Country, Pack("Countries", "Albania")),
        new("Algeria", FlagGroup.Country, Pack("Countries", "Algeria")),
        new("American Samoa", FlagGroup.Country, Pack("Countries", "American Samoa")),
        new("Andorra", FlagGroup.Country, Pack("Countries", "Andorra")),
        new("Angola", FlagGroup.Country, Pack("Countries", "Angola")),
        new("Anguilla", FlagGroup.Country, Pack("Countries", "Anguilla")),
        new("Antarctica", FlagGroup.Country, Pack("Countries", "Antarctica")),
        new("Antigua and Barbuda", FlagGroup.Country, Pack("Countries", "Antigua and Barbuda")),
        new("Argentina", FlagGroup.Country, Pack("Countries", "Argentina")),
        new("Armenia", FlagGroup.Country, Pack("Countries", "Armenia")),
        new("Aruba", FlagGroup.Country, Pack("Countries", "Aruba")),
        new("Australia", FlagGroup.Country, Pack("Countries", "Australia")),
        new("Austria", FlagGroup.Country, Pack("Countries", "Austria")),
        new("Azerbaijan", FlagGroup.Country, Pack("Countries", "Azerbaijan")),
        new("Bahamas", FlagGroup.Country, Pack("Countries", "Bahamas")),
        new("Bahrain", FlagGroup.Country, Pack("Countries", "Bahrain")),
        new("Bangladesh", FlagGroup.Country, Pack("Countries", "Bangladesh")),
        new("Barbados", FlagGroup.Country, Pack("Countries", "Barbados")),
        new("Belarus", FlagGroup.Country, Pack("Countries", "Belarus")),
        new("Belgium", FlagGroup.Country, Pack("Countries", "Belgium")),
        new("Belize", FlagGroup.Country, Pack("Countries", "Belize")),
        new("Benin", FlagGroup.Country, Pack("Countries", "Benin")),
        new("Bermuda", FlagGroup.Country, Pack("Countries", "Bermuda")),
        new("Bhutan", FlagGroup.Country, Pack("Countries", "Bhutan")),
        new("Bolivia", FlagGroup.Country, Pack("Countries", "Bolivia")),
        new("Bonaire, Sint Eustatius and Saba", FlagGroup.Country, Pack("Countries", "Bonaire Sint Eustatius and Saba")),
        new("Bosnia and Herzegovina", FlagGroup.Country, Pack("Countries", "Bosnia and Herzegovina")),
        new("Botswana", FlagGroup.Country, Pack("Countries", "Botswana")),
        new("Bouvet Island", FlagGroup.Country, Pack("Countries", "Bouvet Island")),
        new("Brazil", FlagGroup.Country, Pack("Countries", "Brazil")),
        new("British Indian Ocean Territory", FlagGroup.Country, Pack("Countries", "British Indian Ocean Territory")),
        new("Brunei Darussalam", FlagGroup.Country, Pack("Countries", "Brunei Darussalam")),
        new("Bulgaria", FlagGroup.Country, Pack("Countries", "Bulgaria")),
        new("Burkina Faso", FlagGroup.Country, Pack("Countries", "Burkina Faso")),
        new("Burundi", FlagGroup.Country, Pack("Countries", "Burundi")),
        new("Cabo Verde", FlagGroup.Country, Pack("Countries", "Cabo Verde")),
        new("Cambodia", FlagGroup.Country, Pack("Countries", "Cambodia")),
        new("Cameroon", FlagGroup.Country, Pack("Countries", "Cameroon")),
        new("Canada", FlagGroup.Country, Pack("Countries", "Canada")),
        new("Cayman Islands", FlagGroup.Country, Pack("Countries", "Cayman Islands")),
        new("Central African Republic", FlagGroup.Country, Pack("Countries", "Central African Republic")),
        new("Chad", FlagGroup.Country, Pack("Countries", "Chad")),
        new("Chile", FlagGroup.Country, Pack("Countries", "Chile")),
        new("China", FlagGroup.Country, Pack("Countries", "China")),
        new("Christmas Island", FlagGroup.Country, Pack("Countries", "Christmas Island")),
        new("Cocos (Keeling) Islands", FlagGroup.Country, Pack("Countries", "Cocos Keeling Islands")),
        new("Colombia", FlagGroup.Country, Pack("Countries", "Colombia")),
        new("Comoros", FlagGroup.Country, Pack("Countries", "Comoros")),
        new("Cook Islands", FlagGroup.Country, Pack("Countries", "Cook Islands")),
        new("Costa Rica", FlagGroup.Country, Pack("Countries", "Costa Rica")),
        new("Côte d'Ivoire", FlagGroup.Country, Pack("Countries", "Cote dIvoire")),
        new("Croatia", FlagGroup.Country, Pack("Countries", "Croatia")),
        new("Cuba", FlagGroup.Country, Pack("Countries", "Cuba")),
        new("Curaçao", FlagGroup.Country, Pack("Countries", "Curacao")),
        new("Cyprus", FlagGroup.Country, Pack("Countries", "Cyprus")),
        new("Czech Republic", FlagGroup.Country, Pack("Countries", "Czech Republic")),
        new("Democratic Republic of the Congo", FlagGroup.Country, Pack("Countries", "Democratic Republic of the Congo")),
        new("Denmark", FlagGroup.Country, Pack("Countries", "Denmark")),
        new("Djibouti", FlagGroup.Country, Pack("Countries", "Djibouti")),
        new("Dominica", FlagGroup.Country, Pack("Countries", "Dominica")),
        new("Dominican Republic", FlagGroup.Country, Pack("Countries", "Dominican Republic")),
        new("Ecuador", FlagGroup.Country, Pack("Countries", "Ecuador")),
        new("Egypt", FlagGroup.Country, Pack("Countries", "Egypt")),
        new("El Salvador", FlagGroup.Country, Pack("Countries", "El Salvador")),
        new("Equatorial Guinea", FlagGroup.Country, Pack("Countries", "Equatorial Guinea")),
        new("Eritrea", FlagGroup.Country, Pack("Countries", "Eritrea")),
        new("Estonia", FlagGroup.Country, Pack("Countries", "Estonia")),
        new("Eswatini", FlagGroup.Country, Pack("Countries", "Eswatini")),
        new("Ethiopia", FlagGroup.Country, Pack("Countries", "Ethiopia")),
        new("Falkland Islands", FlagGroup.Country, Pack("Countries", "Falkland Islands")),
        new("Faroe Islands", FlagGroup.Country, Pack("Countries", "Faroe Islands")),
        new("Federated States of Micronesia", FlagGroup.Country, Pack("Countries", "Federated States of Micronesia")),
        new("Fiji", FlagGroup.Country, Pack("Countries", "Fiji")),
        new("Finland", FlagGroup.Country, Pack("Countries", "Finland")),
        new("France", FlagGroup.Country, Pack("Countries", "France")),
        new("French Guiana", FlagGroup.Country, Pack("Countries", "French Guiana")),
        new("French Polynesia", FlagGroup.Country, Pack("Countries", "French Polynesia")),
        new("French Southern Territories", FlagGroup.Country, Pack("Countries", "French Southern Territories")),
        new("Gabon", FlagGroup.Country, Pack("Countries", "Gabon")),
        new("Gambia", FlagGroup.Country, Pack("Countries", "Gambia")),
        new("Georgia", FlagGroup.Country, Pack("Countries", "Georgia")),
        new("Germany", FlagGroup.Country, Pack("Countries", "Germany")),
        new("Ghana", FlagGroup.Country, Pack("Countries", "Ghana")),
        new("Gibraltar", FlagGroup.Country, Pack("Countries", "Gibraltar")),
        new("Greece", FlagGroup.Country, Pack("Countries", "Greece")),
        new("Greenland", FlagGroup.Country, Pack("Countries", "Greenland")),
        new("Grenada", FlagGroup.Country, Pack("Countries", "Grenada")),
        new("Guadeloupe", FlagGroup.Country, Pack("Countries", "Guadeloupe")),
        new("Guam", FlagGroup.Country, Pack("Countries", "Guam")),
        new("Guatemala", FlagGroup.Country, Pack("Countries", "Guatemala")),
        new("Guernsey", FlagGroup.Country, Pack("Countries", "Guernsey")),
        new("Guinea", FlagGroup.Country, Pack("Countries", "Guinea")),
        new("Guinea-Bissau", FlagGroup.Country, Pack("Countries", "Guinea-Bissau")),
        new("Guyana", FlagGroup.Country, Pack("Countries", "Guyana")),
        new("Haiti", FlagGroup.Country, Pack("Countries", "Haiti")),
        new("Heard Island and McDonald Islands", FlagGroup.Country, Pack("Countries", "Heard Island and McDonald Islands")),
        new("Holy See", FlagGroup.Country, Pack("Countries", "Holy See")),
        new("Honduras", FlagGroup.Country, Pack("Countries", "Honduras")),
        new("Hong Kong", FlagGroup.Country, Pack("Countries", "Hong Kong")),
        new("Hungary", FlagGroup.Country, Pack("Countries", "Hungary")),
        new("Iceland", FlagGroup.Country, Pack("Countries", "Iceland")),
        new("India", FlagGroup.Country, Pack("Countries", "India")),
        new("Indonesia", FlagGroup.Country, Pack("Countries", "Indonesia")),
        new("Iran", FlagGroup.Country, Pack("Countries", "Iran")),
        new("Iraq", FlagGroup.Country, Pack("Countries", "Iraq")),
        new("Ireland", FlagGroup.Country, Pack("Countries", "Ireland")),
        new("Isle of Man", FlagGroup.Country, Pack("Countries", "Isle of Man")),
        new("Israel", FlagGroup.Country, Pack("Countries", "Israel")),
        new("Italy", FlagGroup.Country, Pack("Countries", "Italy")),
        new("Jamaica", FlagGroup.Country, Pack("Countries", "Jamaica")),
        new("Japan", FlagGroup.Country, Pack("Countries", "Japan")),
        new("Jersey", FlagGroup.Country, Pack("Countries", "Jersey")),
        new("Jordan", FlagGroup.Country, Pack("Countries", "Jordan")),
        new("Kazakhstan", FlagGroup.Country, Pack("Countries", "Kazakhstan")),
        new("Kenya", FlagGroup.Country, Pack("Countries", "Kenya")),
        new("Kiribati", FlagGroup.Country, Pack("Countries", "Kiribati")),
        new("Kuwait", FlagGroup.Country, Pack("Countries", "Kuwait")),
        new("Kyrgyzstan", FlagGroup.Country, Pack("Countries", "Kyrgyzstan")),
        new("Laos", FlagGroup.Country, Pack("Countries", "Laos")),
        new("Latvia", FlagGroup.Country, Pack("Countries", "Latvia")),
        new("Lebanon", FlagGroup.Country, Pack("Countries", "Lebanon")),
        new("Lesotho", FlagGroup.Country, Pack("Countries", "Lesotho")),
        new("Liberia", FlagGroup.Country, Pack("Countries", "Liberia")),
        new("Libya", FlagGroup.Country, Pack("Countries", "Libya")),
        new("Liechtenstein", FlagGroup.Country, Pack("Countries", "Liechtenstein")),
        new("Lithuania", FlagGroup.Country, Pack("Countries", "Lithuania")),
        new("Luxembourg", FlagGroup.Country, Pack("Countries", "Luxembourg")),
        new("Macau", FlagGroup.Country, Pack("Countries", "Macau")),
        new("Madagascar", FlagGroup.Country, Pack("Countries", "Madagascar")),
        new("Malawi", FlagGroup.Country, Pack("Countries", "Malawi")),
        new("Malaysia", FlagGroup.Country, Pack("Countries", "Malaysia")),
        new("Maldives", FlagGroup.Country, Pack("Countries", "Maldives")),
        new("Mali", FlagGroup.Country, Pack("Countries", "Mali")),
        new("Malta", FlagGroup.Country, Pack("Countries", "Malta")),
        new("Marshall Islands", FlagGroup.Country, Pack("Countries", "Marshall Islands")),
        new("Martinique", FlagGroup.Country, Pack("Countries", "Martinique")),
        new("Mauritania", FlagGroup.Country, Pack("Countries", "Mauritania")),
        new("Mauritius", FlagGroup.Country, Pack("Countries", "Mauritius")),
        new("Mayotte", FlagGroup.Country, Pack("Countries", "Mayotte")),
        new("Mexico", FlagGroup.Country, Pack("Countries", "Mexico")),
        new("Moldova", FlagGroup.Country, Pack("Countries", "Moldova")),
        new("Monaco", FlagGroup.Country, Pack("Countries", "Monaco")),
        new("Mongolia", FlagGroup.Country, Pack("Countries", "Mongolia")),
        new("Montenegro", FlagGroup.Country, Pack("Countries", "Montenegro")),
        new("Montserrat", FlagGroup.Country, Pack("Countries", "Montserrat")),
        new("Morocco", FlagGroup.Country, Pack("Countries", "Morocco")),
        new("Mozambique", FlagGroup.Country, Pack("Countries", "Mozambique")),
        new("Myanmar", FlagGroup.Country, Pack("Countries", "Myanmar")),
        new("Namibia", FlagGroup.Country, Pack("Countries", "Namibia")),
        new("Nauru", FlagGroup.Country, Pack("Countries", "Nauru")),
        new("Nepal", FlagGroup.Country, Pack("Countries", "Nepal")),
        new("Netherlands", FlagGroup.Country, Pack("Countries", "Netherlands")),
        new("New Caledonia", FlagGroup.Country, Pack("Countries", "New Caledonia")),
        new("New Zealand", FlagGroup.Country, Pack("Countries", "New Zealand")),
        new("Nicaragua", FlagGroup.Country, Pack("Countries", "Nicaragua")),
        new("Niger", FlagGroup.Country, Pack("Countries", "Niger")),
        new("Nigeria", FlagGroup.Country, Pack("Countries", "Nigeria")),
        new("Niue", FlagGroup.Country, Pack("Countries", "Niue")),
        new("Norfolk Island", FlagGroup.Country, Pack("Countries", "Norfolk Island")),
        new("North Korea", FlagGroup.Country, Pack("Countries", "North Korea")),
        new("North Macedonia", FlagGroup.Country, Pack("Countries", "North Macedonia")),
        new("Northern Mariana Islands", FlagGroup.Country, Pack("Countries", "Northern Mariana Islands")),
        new("Norway", FlagGroup.Country, Pack("Countries", "Norway")),
        new("Oman", FlagGroup.Country, Pack("Countries", "Oman")),
        new("Pakistan", FlagGroup.Country, Pack("Countries", "Pakistan")),
        new("Palau", FlagGroup.Country, Pack("Countries", "Palau")),
        new("Panama", FlagGroup.Country, Pack("Countries", "Panama")),
        new("Papua New Guinea", FlagGroup.Country, Pack("Countries", "Papua New Guinea")),
        new("Paraguay", FlagGroup.Country, Pack("Countries", "Paraguay")),
        new("Peru", FlagGroup.Country, Pack("Countries", "Peru")),
        new("Philippines", FlagGroup.Country, Pack("Countries", "Philippines")),
        new("Pitcairn", FlagGroup.Country, Pack("Countries", "Pitcairn")),
        new("Poland", FlagGroup.Country, Pack("Countries", "Poland")),
        new("Portugal", FlagGroup.Country, Pack("Countries", "Portugal")),
        new("Puerto Rico", FlagGroup.Country, Pack("Countries", "Puerto Rico")),
        new("Qatar", FlagGroup.Country, Pack("Countries", "Qatar")),
        new("Republic of the Congo", FlagGroup.Country, Pack("Countries", "Republic of the Congo")),
        new("Réunion", FlagGroup.Country, Pack("Countries", "Reunion")),
        new("Romania", FlagGroup.Country, Pack("Countries", "Romania")),
        new("Russia", FlagGroup.Country, Pack("Countries", "Russia")),
        new("Rwanda", FlagGroup.Country, Pack("Countries", "Rwanda")),
        new("Saint Barthélemy", FlagGroup.Country, Pack("Countries", "Saint Barthelemy")),
        new("Saint Helena, Ascension and Tristan da Cunha", FlagGroup.Country, Pack("Countries", "Saint Helena Ascension and Tristan da Cunha")),
        new("Saint Kitts and Nevis", FlagGroup.Country, Pack("Countries", "Saint Kitts and Nevis")),
        new("Saint Lucia", FlagGroup.Country, Pack("Countries", "Saint Lucia")),
        new("Saint Martin", FlagGroup.Country, Pack("Countries", "Saint Martin")),
        new("Saint Pierre and Miquelon", FlagGroup.Country, Pack("Countries", "Saint Pierre and Miquelon")),
        new("Saint Vincent and the Grenadines", FlagGroup.Country, Pack("Countries", "Saint Vincent and the Grenadines")),
        new("Samoa", FlagGroup.Country, Pack("Countries", "Samoa")),
        new("San Marino", FlagGroup.Country, Pack("Countries", "San Marino")),
        new("Sao Tome and Principe", FlagGroup.Country, Pack("Countries", "Sao Tome and Principe")),
        new("Saudi Arabia", FlagGroup.Country, Pack("Countries", "Saudi Arabia")),
        new("Senegal", FlagGroup.Country, Pack("Countries", "Senegal")),
        new("Serbia", FlagGroup.Country, Pack("Countries", "Serbia")),
        new("Seychelles", FlagGroup.Country, Pack("Countries", "Seychelles")),
        new("Sierra Leone", FlagGroup.Country, Pack("Countries", "Sierra Leone")),
        new("Singapore", FlagGroup.Country, Pack("Countries", "Singapore")),
        new("Sint Maarten", FlagGroup.Country, Pack("Countries", "Sint Maarten")),
        new("Slovakia", FlagGroup.Country, Pack("Countries", "Slovakia")),
        new("Slovenia", FlagGroup.Country, Pack("Countries", "Slovenia")),
        new("Solomon Islands", FlagGroup.Country, Pack("Countries", "Solomon Islands")),
        new("Somalia", FlagGroup.Country, Pack("Countries", "Somalia")),
        new("South Africa", FlagGroup.Country, Pack("Countries", "South Africa")),
        new("South Georgia and the South Sandwich Islands", FlagGroup.Country, Pack("Countries", "South Georgia and the South Sandwich Islands")),
        new("South Korea", FlagGroup.Country, Pack("Countries", "South Korea")),
        new("South Sudan", FlagGroup.Country, Pack("Countries", "South Sudan")),
        new("Spain", FlagGroup.Country, Pack("Countries", "Spain")),
        new("Sri Lanka", FlagGroup.Country, Pack("Countries", "Sri Lanka")),
        new("State of Palestine", FlagGroup.Country, Pack("Countries", "State of Palestine")),
        new("Sudan", FlagGroup.Country, Pack("Countries", "Sudan")),
        new("Suriname", FlagGroup.Country, Pack("Countries", "Suriname")),
        new("Svalbard and Jan Mayen", FlagGroup.Country, Pack("Countries", "Svalbard and Jan Mayen")),
        new("Sweden", FlagGroup.Country, Pack("Countries", "Sweden")),
        new("Switzerland", FlagGroup.Country, Pack("Countries", "Switzerland")),
        new("Syria", FlagGroup.Country, Pack("Countries", "Syria")),
        new("Taiwan", FlagGroup.Country, Pack("Countries", "Taiwan")),
        new("Tajikistan", FlagGroup.Country, Pack("Countries", "Tajikistan")),
        new("Tanzania", FlagGroup.Country, Pack("Countries", "Tanzania")),
        new("Thailand", FlagGroup.Country, Pack("Countries", "Thailand")),
        new("Timor-Leste", FlagGroup.Country, Pack("Countries", "Timor-Leste")),
        new("Togo", FlagGroup.Country, Pack("Countries", "Togo")),
        new("Tokelau", FlagGroup.Country, Pack("Countries", "Tokelau")),
        new("Tonga", FlagGroup.Country, Pack("Countries", "Tonga")),
        new("Trinidad and Tobago", FlagGroup.Country, Pack("Countries", "Trinidad and Tobago")),
        new("Tunisia", FlagGroup.Country, Pack("Countries", "Tunisia")),
        new("Türkiye", FlagGroup.Country, Pack("Countries", "Turkiye")),
        new("Turkmenistan", FlagGroup.Country, Pack("Countries", "Turkmenistan")),
        new("Turks and Caicos Islands", FlagGroup.Country, Pack("Countries", "Turks and Caicos Islands")),
        new("Tuvalu", FlagGroup.Country, Pack("Countries", "Tuvalu")),
        new("Uganda", FlagGroup.Country, Pack("Countries", "Uganda")),
        new("Ukraine", FlagGroup.Country, Pack("Countries", "Ukraine")),
        new("United Arab Emirates", FlagGroup.Country, Pack("Countries", "United Arab Emirates")),
        new("United Kingdom", FlagGroup.Country, Pack("Countries", "United Kingdom")),
        new("United States Minor Outlying Islands", FlagGroup.Country, Pack("Countries", "United States Minor Outlying Islands")),
        new("United States of America", FlagGroup.Country, Pack("Countries", "United States of America")),
        new("Uruguay", FlagGroup.Country, Pack("Countries", "Uruguay")),
        new("Uzbekistan", FlagGroup.Country, Pack("Countries", "Uzbekistan")),
        new("Vanuatu", FlagGroup.Country, Pack("Countries", "Vanuatu")),
        new("Venezuela", FlagGroup.Country, Pack("Countries", "Venezuela")),
        new("Vietnam", FlagGroup.Country, Pack("Countries", "Vietnam")),
        new("Virgin Islands (British)", FlagGroup.Country, Pack("Countries", "Virgin Islands British")),
        new("Virgin Islands (U.S.)", FlagGroup.Country, Pack("Countries", "Virgin Islands US")),
        new("Wallis and Futuna", FlagGroup.Country, Pack("Countries", "Wallis and Futuna")),
        new("Western Sahara", FlagGroup.Country, Pack("Countries", "Western Sahara")),
        new("Yemen", FlagGroup.Country, Pack("Countries", "Yemen")),
        new("Zambia", FlagGroup.Country, Pack("Countries", "Zambia")),
        new("Zimbabwe", FlagGroup.Country, Pack("Countries", "Zimbabwe")),
    };

    public static readonly IReadOnlyList<FlagIconEntry> All = States.Concat(Countries).ToList();
}
